name: deploy-book

# Run this when main branch changes
on:
  push:
    branches:
    - master
    - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        repository: guenp/cookiecutter-data-warehouse
        token: ${{ secrets.GH_PAT }}

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Run cookie cutter
    - name: Set up new project from cookie cutter
      run: |
        cd ..
        pip install cookiecutter
        cookiecutter --no-input cookiecutter-data-warehouse

    - name: Install dependencies
      working-directory: ./ducky_data_warehouse/book
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      working-directory: ./ducky_data_warehouse/book
      run: |
        jupyter-book build book

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "./ducky_data_warehouse/book/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2